
server:
  port: 8000

spring:
  application:
    name: keycloak
  thymeleaf:
    enabled: true
    check-template-location: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization grant type: authorization_code
            client-id: my_client
            client-secret: KMZgIDxHBGcc4XmSdij8nYS95aUGcNp9
            redirect-uri: http://localhost:8000/login/oauth2/code/keycloak
            clientAuthenticationMethod: client_secret_post
            scope: openid,email
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/my_realm/protocol/openid-connect/auth
            issuer-uri: http://localhost:8080/realms/my_realm






